USE oscar;
INSERT INTO film(navn) VALUES
(" American Sniper "),
(" Birdman or (The Unexpected Virtue of Ignorance) "),
(" Boyhood "),
(" The Grand Budapest Hotel "),
(" The Imitation Game "),
(" Selma "),
(" The Theory of Everything "),
(" Whiplash "),
(" Foxcatcher "),
(" Two Days, One Night "),
(" Still Alice "),
(" Gone Girl "),
(" Wild "),
(" The Judge "),
(" Into the Woods "),
(" Big Hero 6 "),
(" The Boxtrolls "),
(" How to Train Your Dragon 2 "),
(" Song of the Sea "),
(" The Tale of the Princess Kaguya "),
(" Ida "),
(" Mr. Turner "),
(" Unbroken "),
(" Inherent Vice "),
(" Maleficent "),
(" CitizenFour "),
(" Finding Vivian Maier "),
(" Last Days in Vietnam "),
(" The Salt of the Earth "),
(" Virunga "),
(" Crisis Hotline: Veterans Press 1 "),
(" Joanna "),
(" Our Curse "),
(" The Reaper (La Parka) "),
(" White Earth "),
(" Leviathan "),
(" Tangerines "),
(" Timbuktu "),
(" Wild Tales "),
(" Guardians of the Galaxy "),
(" Interstellar "),
(" THE LEGO MOVIE "),
(" BEYOND THE LIGHTS "),
(" GLEN CAMPBELL...I'LL BE ME "),
(" BEGIN AGAIN "),
(" The Bigger Picture "),
(" The Dam Keeper "),
(" Feast "),
(" Me and My Moulton "),
(" A Single Life "),
(" Aya "),
(" Boogaloo and Graham "),
(" Butter Lamp (La Lampe au Beurre de Yak) "),
(" Parvaneh "),
(" The Phone Call "),
(" The Hobbit: The Battle of the Five Armies "),
(" Captain America: The Winter Soldier "),
(" Dawn of the Planet of the Apes "),
(" X-Men: Days of Future Past "),
(" Nightcrawler ");

INSERT INTO kategori(navn) VALUES
(" Best Picture "),
(" Actor in a Leading Role "),
(" Actress in a Leading Role "),
(" Actor in a Supporting Role "),
(" Actress in a Supporting Role "),
(" Animated Feature Film "),
(" Cinematography "),
(" Costume Design "),
(" Directing "),
(" Documentary Feature "),
(" Documentary Short Subject "),
(" Film Editing "),
(" Foreign Language Film "),
(" Makeup and Hairstyling "),
(" Music Original Score "),
(" Music Original Song "),
(" Production Design "),
(" Short Film Animated "),
(" Short Film Live Action "),
(" Sound Editing "),
(" Sound Mixing "),
(" Visual Effects "),
(" Writing Adapted Screenplay "),
(" Writing Original Screenplay ");

INSERT INTO nominering(film,kategori,note) VALUES
( 0 , 0 ," Clint Eastwood, Robert Lorenz, Andrew Lazar, Bradley Cooper and Peter Morgan "),
( 1 , 0 ," Alejandro G. Iñárritu, John Lesher and James W. Skotchdopole "),
( 2 , 0 ," Richard Linklater and Cathleen Sutherland "),
( 3 , 0 ," Wes Anderson, Scott Rudin, Steven Rales and Jeremy Dawson "),
( 4 , 0 ," Nora Grossman, Ido Ostrowsky and Teddy Schwarzman "),
( 5 , 0 ," Christian Colson, Oprah Winfrey, Dede Gardner and Jeremy Kleiner "),
( 6 , 0 ," Tim Bevan, Eric Fellner, Lisa Bruce and Anthony McCarten "),
( 7 , 0 ," Jason Blum, Helen Estabrook and David Lancaster "),
( 8 , 1 ," Steve Carell "),
( 0 , 1 ," Bradley Cooper "),
( 4 , 1 ," Benedict Cumberbatch "),
( 1 , 1 ," Michael Keaton "),
( 6 , 1 ," Eddie Redmayne "),
( 9 , 2 ," Marion Cotillard "),
( 6 , 2 ," Felicity Jones "),
( 10 , 2 ," Julianne Moore "),
( 11 , 2 ," Rosamund Pike "),
( 12 , 2 ," Reese Witherspoon "),
( 13 , 3 ," Robert Duvall "),
( 2 , 3 ," Ethan Hawke "),
( 1 , 3 ," Edward Norton "),
( 8 , 3 ," Mark Ruffalo "),
( 7 , 3 ," J.K. Simmons "),
( 2 , 4 ," Patricia Arquette "),
( 12 , 4 ," Laura Dern "),
( 4 , 4 ," Keira Knightley "),
( 1 , 4 ," Emma Stone "),
( 14 , 4 ," Meryl Streep "),
( 15 , 5 ," Don Hall, Chris Williams and Roy Conli "),
( 16 , 5 ," Anthony Stacchi, Graham Annable and Travis Knight "),
( 17 , 5 ," Dean DeBlois and Bonnie Arnold "),
( 18 , 5 ," Tomm Moore and Paul Young "),
( 19 , 5 ," Isao Takahata and Yoshiaki Nishimura "),
( 1 , 6 ," Emmanuel Lubezki "),
( 3 , 6 ," Robert Yeoman "),
( 20 , 6 ," Lukasz Zal and Ryszard Lenczewski "),
( 21 , 6 ," Dick Pope "),
( 22 , 6 ," Roger Deakins "),
( 3 , 7 ," Milena Canonero "),
( 23 , 7 ," Mark Bridges "),
( 14 , 7 ," Colleen Atwood "),
( 24 , 7 ," Anna B. Sheppard and Jane Clive "),
( 21 , 7 ," Jacqueline Durran "),
( 1 , 8 ," Alejandro G. Iñárritu "),
( 2 , 8 ," Richard Linklater "),
( 8 , 8 ," Bennett Miller "),
( 3 , 8 ," Wes Anderson "),
( 4 , 8 ," Morten Tyldum "),
( 25 , 9 ," Laura Poitras, Mathilde Bonnefoy and Dirk Wilutzky "),
( 26 , 9 ," John Maloof and Charlie Siskel "),
( 27 , 9 ," Rory Kennedy and Keven McAlester "),
( 28 , 9 ," Wim Wenders, Juliano Ribeiro Salgado and David Rosier "),
( 29 , 9 ," Orlando von Einsiedel and Joanna Natasegara "),
( 30 , 10 ," Ellen Goosenberg Kent and Dana Perry "),
( 31 , 10 ," Aneta Kopacz "),
( 32 , 10 ," Tomasz &Sacute;liwi&nacute;ski and Maciej &Sacute;lesicki "),
( 33 , 10 ," Gabriel Serra Arguello "),
( 34 , 10 ," J. Christian Jensen "),
( 0 , 11 ," Joel Cox and Gary D. Roach "),
( 2 , 11 ," Sandra Adair "),
( 3 , 11 ," Barney Pilling "),
( 4 , 11 ," William Goldenberg "),
( 7 , 11 ," Tom Cross "),
( 20 , 12 ," Poland; Directed by Pawel Pawlikowski "),
( 35 , 12 ," Russia; Directed by Andrey Zvyagintsev "),
( 36 , 12 ," Estonia; Directed by Zaza Urushadze "),
( 37 , 12 ," Mauritania; Directed by Abderrahmane Sissako "),
( 38 , 12 ," Argentina; Directed by Damián Szifron "),
( 8 , 13 ," Bill Corso and Dennis Liddiard "),
( 3 , 13 ," Frances Hannon and Mark Coulier "),
( 39 , 13 ," Elizabeth Yianni-Georgiou and David White "),
( 3 , 14 ," Alexandre Desplat "),
( 4 , 14 ," Alexandre Desplat "),
( 40 , 14 ," Hans Zimmer "),
( 21 , 14 ," Gary Yershon "),
( 6 , 14 ," Jóhann Jóhannsson "),
( 41 , 15 ," Everything Is Awesome - Music and Lyric by Shawn Patterson "),
( 5 , 15 ," Glory - Music and Lyric by John Stephens and Lonnie Lynn "),
( 42 , 15 ," Grateful - Music and Lyric by Diane Warren "),
( 43 , 15 ," I'm Not Gonna Miss You - Music and Lyric by Glen Campbell and Julian Raymond "),
( 44 , 15 ," Lost Stars - Music and Lyric by Gregg Alexander and Danielle Brisebois "),
( 3 , 16 ," Adam Stockhausen (Production Design); Anna Pinnock (Set Decoration) "),
( 4 , 16 ," Maria Djurkovic (Production Design); Tatiana Macdonald (Set Decoration) "),
( 40 , 16 ," Nathan Crowley (Production Design); Gary Fettis (Set Decoration) "),
( 14 , 16 ," Dennis Gassner (Production Design); Anna Pinnock (Set Decoration) "),
( 21 , 16 ," Suzie Davies (Production Design); Charlotte Watts (Set Decoration) "),
( 45 , 17 ," Daisy Jacobs and Christopher Hees "),
( 46 , 17 ," Robert Kondo and Dice Tsutsumi "),
( 47 , 17 ," Patrick Osborne and Kristina Reed "),
( 48 , 17 ," Torill Kove "),
( 49 , 17 ," Joris Oprins "),
( 50 , 18 ," Oded Binnun and Mihal Brezis "),
( 51 , 18 ," Michael Lennox and Ronan Blaney "),
( 52 , 18 ," Hu Wei and Julien Féret "),
( 53 , 18 ," Talkhon Hamzavi and Stefan Eichenberger "),
( 54 , 18 ," Mat Kirkby and James Lucas "),
( 0 , 19 ," Alan Robert Murray and Bub Asman "),
( 1 , 19 ," Martin Hernández and Aaron Glascock "),
( 55 , 19 ," Brent Burge and Jason Canovas "),
( 40 , 19 ," Richard King "),
( 22 , 19 ," Becky Sullivan and Andrew DeCristofaro "),
( 0 , 20 ," John Reitz, Gregg Rudloff and Walt Martin "),
( 1 , 20 ," Jon Taylor, Frank A. Montaño and Thomas Varga "),
( 40 , 20 ," Gary A. Rizzo, Gregg Landaker and Mark Weingarten "),
( 22 , 20 ," Jon Taylor, Frank A. Montaño and David Lee "),
( 7 , 20 ," Craig Mann, Ben Wilkins and Thomas Curley "),
( 56 , 21 ," Dan DeLeeuw, Russell Earl, Bryan Grill and Dan Sudick "),
( 57 , 21 ," Joe Letteri, Dan Lemmon, Daniel Barrett and Erik Winquist "),
( 39 , 21 ," Stephane Ceretti, Nicolas Aithadi, Jonathan Fawkner and Paul Corbould "),
( 40 , 21 ," Paul Franklin, Andrew Lockley, Ian Hunter and Scott Fisher "),
( 58 , 21 ," Richard Stammers, Lou Pecora, Tim Crosbie and Cameron Waldbauer "),
( 0 , 22 ," Written by Jason Hall "),
( 4 , 22 ," Written by Graham Moore "),
( 23 , 22 ," Written for the screen by Paul Thomas Anderson "),
( 6 , 22 ," Screenplay by Anthony McCarten "),
( 7 , 22 ," Written by Damien Chazelle "),
( 1 , 23 ," Written by Alejandro G. Iñárritu, Nicolás Giacobone, Alexander Dinelaris, Jr. & Armando Bo "),
( 2 , 23 ," Written by Richard Linklater "),
( 8 , 23 ," Written by E. Max Frye and Dan Futterman "),
( 3 , 23 ," Screenplay by Wes Anderson; Story by Wes Anderson & Hugo Guinness "),
( 59 , 23 ," Written by Dan Gilroy ");
