USE oscar;

INSERT INTO film(navn) VALUES 
('12 Years a Slave'),
('20 Feet from Stardom'),
('All Is Lost'),
('American Hustle'),
('Aquel No Era Yo (That Wasn’t Me)'),
('August: Osage County'),
('Avant Que De Tout Perdre (Just before Losing Everything)'),
('Before Midnight'),
('Blue Jasmine'),
('Captain Phillips'),
('CaveDigger'),
('Cutie and the Boxer'),
('Dallas Buyers Club'),
('Despicable Me 2'),
('Dirty Wars'),
('Ernest &amp; Celestine'),
('Facing Fear'),
('Feral'),
('Frozen'),
('Get a Horse!'),
('Gravity'),
('Happy'),
('Helium'),
('Her'),
('Inside Llewyn Davis'),
('Iron Man 3'),
('Jackass Presents: Bad Grandpa'),
('Karama Has No Walls'),
('Let It Go'),
('Lone Survivor'),
('Mandela: Long Walk to Freedom'),
('Mr. Hublot'),
('Nebraska'),
('Omar'),
('Ordinary Love'),
('Philomena'),
('Pitääkö Mun  Kaikki Hoitaa? (Do I Have to Take Care of Everything?)'),
('Possessions'),
('Prison Terminal: The Last Days of Private Jack Hall'),
('Prisoners'),
('Room on the Broom'),
('Saving Mr. Banks'),
('Star Trek Into Darkness'),
('The Act of Killing'),
('The Book Thief'),
('The Broken Circle Breakdown'),
('The Croods'),
('The Grandmaster'),
('The Great Beauty'),
('The Great Gatsby'),
('The Hobbit: The Desolation of Smaug'),
('The Hunt'),
('The Invisible Woman'),
('The Lady in Number 6: Music Saved My Life'),
('The Lone Ranger'),
('The Missing Picture'),
('The Moon Song'),
('The Square'),
('The Voorman Problem'),
('The Wind Rises'),
('The Wolf of Wall Street');


INSERT INTO `guess` VALUES (1,1);

INSERT INTO kategori(navn) VALUES 
('Best Actor'),
('Best Actress'),
('Best Animated Feature Film'),
('Best Animated Short Film'),
('Best Cinematography'),
('Best Costume Design'),
('Best Dcumentary - Feature'),
('Best Director'),
('Best Documentary - Short Subject'),
('Best Film Editing'),
('Best Foreign Langauge Film'),
('Best Live Action Short Film'),
('Best Makeup and Hairstyling'),
('Best Original Score'),
('Best Original Song'),
('Best Picture'),
('Best Production Design'),
('Best Sound Editing'),
('Best Sound Mixing'),
('Best Supporting Actor'),
('Best Supporting Actress'),
('Best VIsual Effects'),
('Best Writing - Adapted Screenplay'),
('Best Writing - Original Screenplay');



INSERT INTO nominering(film,kategori,note,winner) VALUES 
(1,1,'Christian Bale','\0'),
(2,1,'Bruce Dern','\0'),
(3,1,'Leonardo DiCaprio','\0'),
(4,1,'Chiwetel Ejiofor','\0'),
(5,1,'Matthew McConaughey','\0');
--#(,,'','\0\),



INSERT INTO user(navn,hash) VALUES ('testbruger1','42');
