CREATE DATABASE IF NOT EXISTS oscar;
USE oscar;

DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
  id int(11) NOT NULL AUTO_INCREMENT,
  title varchar(200) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS guess;

CREATE TABLE guess (
  user int(11) DEFAULT NULL,
  nomination int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS category;

CREATE TABLE category (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(200) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS nominations;

CREATE TABLE nominations (
  id int(11) NOT NULL AUTO_INCREMENT,
  movie int(11) DEFAULT NULL,
  category int(11) DEFAULT NULL,
  note varchar(200) DEFAULT NULL,
  winner int(1) DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(45) DEFAULT NULL,
  hash varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
